# Generated by Django 4.2.10 on 2026-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('title', models.CharField(max_length=200, verbose_name='Kasb')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('profile_image', models.ImageField(upload_to='profile/', verbose_name='Profil rasmi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('address', models.CharField(max_length=200, verbose_name='Manzil')),
                ('education', models.CharField(max_length=200, verbose_name="O'qish joyi")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('github', models.CharField(max_length=100, verbose_name='GitHub username')),
            ],
            options={
                'verbose_name': 'Men haqimda',
                'verbose_name_plural': 'Men haqimda',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('category', models.CharField(choices=[('web', 'Veb-sayt'), ('bot', 'Telegram Bot'), ('iot', 'IoT'), ('mobile', 'Mobil')], max_length=20, verbose_name='Kategoriya')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Rasm')),
                ('technologies', models.CharField(max_length=200, verbose_name='Texnologiyalar')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub link')),
                ('live_link', models.URLField(blank=True, verbose_name='Demo link')),
                ('featured', models.BooleanField(default=False, verbose_name='Muhim loyiha')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-featured', '-created_date'],
            },
        ),
    ]
